language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
notifications:
  email: false
after_success:
  - npm run coveralls
  - npm run codeclimate
before_install:
  - npm i -g yarn
install:
  - yarn
